import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Nav from '@/components/Nav'
import Top from '@/components/Top'
import AboutMe from '@/components/AboutMe'
import Skills from '@/components/Skills';
import Projects from '@/components/Projects'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/* <Nav/> */}

      <div className='snap-y snap-mandatory h-screen overflow-scroll scroll-smooth'>
        <div className='h-screen snap-start'><Top/></div>

        <div className='h-screen snap-start'><AboutMe/></div>

        <div className='h-screen snap-start'><Skills/></div>

        <div className='h-screen snap-start'><Projects/></div>
      </div>

    </>
  )
}
