import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Nav from '@/components/Nav'
import Top from '@/components/Top'
import AboutMe from '@/components/AboutMe'
import Skills from '@/components/Skills';
import Projects from '@/components/Projects';
import ContactMe from '@/components/ContactMe';
import SendModal from '@/components/SendModal';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Parker Archibald</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/profile.png" />
      </Head>
      
      <Nav className=''/>

      <div className='snap-y snap-mandatory h-screen overflow-y-scroll overflow-x-hidden scroll-smooth scrollbar-thin scrollbar-track-gray-0/20 scrollbar-thumb-blue-400/80'>
        <div className='h-screen snap-start' id='top'><Top/></div>

        <div className='h-screen snap-start' id='aboutMe'><AboutMe/></div>

        <div className='h-screen snap-start' id='skills'><Skills/></div>

        <div className='h-screen snap-start' id='projects'><Projects/></div>

        <div className='h-screen snap-start' id='contact'><ContactMe/></div>
      </div>

      <SendModal/>
    </>
  )
}
